dist: xenial
language: python
addons:
  apt:
    packages:
      - python3-pip
      - samtools
python:
  - "3.6"
install: python setup.py install
script: python -m unittest discover -s tests -p "*.py"
